name: Run e2e Tests
#1
on:
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t your-docker-username/your-image-name:${{ github.sha }} .

      - name: Run e2e tests
        run: |
          npm run e2e

