name: Build and Run End-to-End Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for e2e tests
      run: docker build -t calc-e2e-test .

    - name: Run end-to-end tests
      run: |
        chmod +x ./e2e-tests.sh
        ./e2e-tests.sh calc-e2e-test
