name: Run Linter

on:
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck --error-exitcode=1 --std=c99 ./
